// ─────────────────────────────────────────────────────────────────────────────
// env-config.js — Runtime environment configuration
//
// IN PRODUCTION (GitHub Pages):
//   This file is auto-generated by the GitHub Actions deploy workflow.
//   It is NEVER committed to the repository.
//   The workflow reads SUPABASE_URL and SUPABASE_ANON_KEY from GitHub Secrets
//   and writes them here at build time.
//
// IN LOCAL DEVELOPMENT:
//   Fill in your anon key below. Do NOT commit this file with real credentials.
//   Add env-config.js to .gitignore.
// ─────────────────────────────────────────────────────────────────────────────

window.__ENV__ = {
  SUPABASE_URL:      'https://xsvqqdhpuiqverpjqqnh.supabase.co',
  SUPABASE_ANON_KEY: 'REPLACE_WITH_YOUR_ANON_KEY_FOR_LOCAL_DEV'
};
